
CREATE TABLE tb_nsf (
	NSF_KEY     INT(11) NOT NULL AUTO_INCREMENT COMMENT 'NSF키',
    NAME        VARCHAR(255) DEFAULT NULL COMMENT 'NSF명',
    PROCESSING  VARCHAR(30) DEFAULT NULL COMMENT '프로세싱',
    INBOUND     VARCHAR(30) DEFAULT NULL COMMENT '인바운드',
    OUTBOUND    VARCHAR(30) DEFAULT NULL COMMENT '아웃바운드',
    INITIATED   VARCHAR(5) DEFAULT NULL COMMENT '활성화여부',
	INSDATE     DATETIME NOT NULL COMMENT '생성일시',
	INSUSER     VARCHAR(18) DEFAULT 'system' COMMENT '생성자',
	UPDDATE     DATETIME NOT NULL COMMENT '수정일시',
	UPDUSER     VARCHAR(18) DEFAULT 'system' COMMENT '수정자',
	PRIMARY KEY (NSF_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='NSF';

CREATE TABLE tb_capability (
    CAPABILITY_KEY  INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Capability키',
	NSF_KEY         INT(11) NOT NULL COMMENT 'NSF키',
    NAME            VARCHAR(255) DEFAULT NULL COMMENT 'Capability 명',
	INSDATE         DATETIME NOT NULL COMMENT '생성일시',
	INSUSER         VARCHAR(18) DEFAULT 'system' COMMENT '생성자',
	UPDDATE         DATETIME NOT NULL COMMENT '수정일시',
	UPDUSER         VARCHAR(18) DEFAULT 'system' COMMENT '수정자',
	PRIMARY KEY (CAPABILITY_KEY, NSF_KEY),
	CONSTRAINT FK_CAPABILITY_01 FOREIGN KEY (NSF_KEY) REFERENCES tb_nsf (NSF_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Capability';

CREATE TABLE tb_field (
	FIELD_KEY       INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Field키',
    CAPABILITY_KEY  INT(11) NOT NULL COMMENT 'Capability키',
	NSF_KEY         INT(11) NOT NULL COMMENT 'NSF키',
    NAME            VARCHAR(255) DEFAULT NULL COMMENT '필드명',
	INSDATE         DATETIME NOT NULL COMMENT '생성일시',
	INSUSER         VARCHAR(18) DEFAULT 'system' COMMENT '생성자',
	UPDDATE         DATETIME NOT NULL COMMENT '수정일시',
	UPDUSER         VARCHAR(18) DEFAULT 'system' COMMENT '수정자',
    PRIMARY KEY (FIELD_KEY,CAPABILITY_KEY,NSF_KEY),
    CONSTRAINT FK_FIELD_01 FOREIGN KEY (CAPABILITY_KEY, NSF_KEY) REFERENCES tb_capability (CAPABILITY_KEY, NSF_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='정책 데이터 필드';

CREATE TABLE tb_service_template (
	SERVICE_TEMPLATE_KEY INT(11) NOT NULL COMMENT '서비스템플릿키',
	NAME                 VARCHAR(100) DEFAULT NULL COMMENT '서비스템플릿명',
	TOPOLOGY_JSON         MEDIUMTEXT DEFAULT NULL COMMENT '토폴로지데이터',
	LINK_JSON            MEDIUMTEXT DEFAULT NULL COMMENT '자원연결데이터',
	DESCRIPTION          VARCHAR(500) DEFAULT NULL COMMENT '설명',
	INSDATE              DATETIME NOT NULL COMMENT '생성일시',
	INSUSER              VARCHAR(18) DEFAULT 'system' COMMENT '생성자',
	UPDDATE              DATETIME NOT NULL COMMENT '수정일시',
	UPDUSER              VARCHAR(18) DEFAULT 'system' COMMENT '수정자',
	PRIMARY KEY (SERVICE_TEMPLATE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='서비스템플릿';


CREATE TABLE tb_endpoint (
    ENDPOINT_KEY         INT(11) NOT NULL AUTO_INCREMENT COMMENT 'endpoint키',
	DOMAIN_KEY           mediumint(9) NOT NULL COMMENT '도메인키',
    NAME                 VARCHAR(255) DEFAULT NULL COMMENT 'endpoint명',
    METADATA             VARCHAR(255) DEFAULT NULL COMMENT 'metadata',
    ENDPOINT_TYPE        VARCHAR(18) DEFAULT NULL COMMENT 'endpoint타입',
	INSDATE              DATETIME NOT NULL COMMENT '생성일시',
	INSUSER              VARCHAR(18) DEFAULT 'system' COMMENT '생성자',
	UPDDATE              DATETIME NOT NULL COMMENT '수정일시',
	UPDUSER              VARCHAR(18) DEFAULT 'system' COMMENT '수정자',
    PRIMARY KEY (ENDPOINT_KEY,DOMAIN_KEY),
    CONSTRAINT FK_ENDPOINT_01 FOREIGN KEY (DOMAIN_KEY) REFERENCES tb_domains (DOMAIN_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='endpoint';

CREATE TABLE tb_fw_rule (
	RULE_KEY             INT(11) NOT NULL COMMENT '규칙키',
	DOMAIN_KEY           mediumint(9) NOT NULL COMMENT '도메인키',
	RULE_NAME            VARCHAR(100) DEFAULT NULL COMMENT '규칙명',
	POLICY_NAME          VARCHAR(100) DEFAULT NULL COMMENT '정책명',
	SOURCE_TARGET        INT(11) NOT NULL COMMENT '출발지',
	DESTINATION_TARGET   INT(11) NOT NULL COMMENT '목적지',
	START_TIME           VARCHAR(18) DEFAULT NULL COMMENT '시작시간',
	END_TIME             VARCHAR(18) DEFAULT NULL COMMENT '종료시간',
	ACTION_DATA          VARCHAR(18) DEFAULT NULL COMMENT '액션',
	DESCRIPTION          VARCHAR(500) DEFAULT NULL COMMENT '설명',
	INSDATE              DATETIME NOT NULL COMMENT '생성일시',
	INSUSER              VARCHAR(18) DEFAULT 'system' COMMENT '생성자',
	UPDDATE              DATETIME NOT NULL COMMENT '수정일시',
	UPDUSER              VARCHAR(18) DEFAULT 'system' COMMENT '수정자',
	PRIMARY KEY (DOMAIN_KEY, RULE_KEY),
	CONSTRAINT FK_FW_RULE_01 FOREIGN KEY (DOMAIN_KEY) REFERENCES tb_domains (DOMAIN_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='방화벽 규칙';





--DELIMITER ;;
--CREATE TRIGGER tb_nsf_DateTime_DEFAULT
--BEFORE INSERT
--    ON tb_nsf FOR EACH ROW
--BEGIN
--    SET NEW.INSDATE = NOW();
--    SET NEW.UPDDATE = NOW();
--END ;;
--
--
--CREATE TRIGGER tb_capability_DateTime_DEFAULT
--BEFORE INSERT
--    ON tb_capability FOR EACH ROW
--BEGIN
--    SET NEW.INSDATE = NOW();
--    SET NEW.UPDDATE = NOW();
--END ;;
--
--CREATE TRIGGER tb_field_DateTime_DEFAULT
--BEFORE INSERT
--    ON tb_field FOR EACH ROW
--BEGIN
--    SET NEW.INSDATE = NOW();
--    SET NEW.UPDDATE = NOW();
--END ;;
--
--CREATE TRIGGER tb_service_template_DateTime_DEFAULT
--BEFORE INSERT
--    ON tb_service_template FOR EACH ROW
--BEGIN
--    SET NEW.INSDATE = NOW();
--    SET NEW.UPDDATE = NOW();
--END ;;
--
-- CREATE TRIGGER tb_endpoint_DateTime_DEFAULT
--BEFORE INSERT
--    ON tb_endpoint FOR EACH ROW
--BEGIN
--    SET NEW.INSDATE = NOW();
--    SET NEW.UPDDATE = NOW();
--END ;;
--
--
--CREATE TRIGGER tb_fw_rule_DateTime_DEFAULT
--BEFORE INSERT
--    ON tb_fw_rule FOR EACH ROW
--BEGIN
--    SET NEW.INSDATE = NOW();
--    SET NEW.UPDDATE = NOW();
--END ;;
--
--DELIMITER ;
